#include-once

Global Const $MM_VERSION_NUMBER = "0.90.4.2"
Global Const $MM_VERSION_SUBTYPE = "beta"
Global Const $MM_VERSION_NAME = "No regrets"
Global Const $MM_VERSION = $MM_VERSION_SUBTYPE == "release" ? $MM_VERSION_NUMBER : ($MM_VERSION_NUMBER & "." & $MM_VERSION_SUBTYPE)

Global Const $MM_TITLE = StringFormat("Era II Mod Manager [%s - %s]", $MM_VERSION, $MM_VERSION_NAME)
Global Const $MM_WINDOW_MIN_WIDTH = 800
Global Const $MM_WINDOW_MIN_HEIGHT = 494

Global Enum $MM_VIEW_MODS, $MM_VIEW_PLUGINS, $MM_VIEW_INSTALL, $MM_VIEW_TOTAL

Global Enum $PLUGIN_GROUP_GLOBAL, $PLUGIN_GROUP_BEFORE, $PLUGIN_GROUP_AFTER
Global Enum $PLUGIN_FILENAME, $PLUGIN_PATH, $PLUGIN_GROUP, $PLUGIN_CAPTION, $PLUGIN_DESCRIPTION, $PLUGIN_STATE, $PLUGIN_DEFAULT_STATE, $PLUGIN_HIDDEN, $PLUGIN_TOTAL

Global Enum $MOD_ID, $MOD_IS_ENABLED, $MOD_IS_EXIST, $MOD_INFO_FILE, $MOD_INFO_PARSED, $MOD_ITEM_ID, $MOD_PARENT_ID, $MOD_TOTAL

Global Enum $MM_LNG_FILE, $MM_LNG_CODE, $MM_LNG_NAME, $MM_LNG_MENU_ID, $MM_LNG_TOTAL